server:
  port: 8088
cas:
  service:
    my-properties:
      author: xl
      age: 23
spring:
  aop:
    auto: true
# 日志配置
logging:
  config: classpath:logback-spring.xml
jmj:
  ips:
    - 10.27.0.1
    - 10.28.0.2
  weights: # 权重，与ips数据对应,加权随机
    - 1
    - 3
  port: 8889
  index: 0x43